# See here for image contents: https://github.com/devcontainers/images/tree/main/src/go

ARG VARIANT="1.27-bookworm"
FROM mcr.microsoft.com/devcontainers/go:${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment the next lines to use go get to install anything else you need
# USER vscode
# RUN go get -x <your-dependency-or-tool>

